### ISSUE TITLE
Using kms_encrypted in fixtures

### ISSUE THREAD

**Issue by robins35** [ankane/kms_encrypted#25]
Is there an easy way to encrypt a value for a fixture? I'd need the `encrypted_kms_key` as well as the `#{column_name}_ciphertext` I assume, and since it's setting these columns directly on a fixture, there is no record id for the context.

I can do `KmsEncrypted::Box.new.encrypt("Hello World!")`, but I figure I need to split that value up afterwards between the two columns (`encrypted_kms_key` and `#{column_name}_ciphertext`).

Here is an example of my chat_messages.yml fixture when I was just using lockbox:
```
one:
  id: 1
  peer_room: one
  peer_room_person: one
  message_time: "2021-06-18 12:10:33.879135-04"
  message_date: Wed, 17 Jun 2020 12:10:33 UTC +00:00
  message_text_ciphertext: <%= ChatMessage.generate_message_text_ciphertext(Lockbox.master_key).inspect %>
  topic_ciphertext: <%= ChatMessage.generate_topic_ciphertext(Lockbox.master_key).inspect %>
```

How would I convert this to use kms_encrypted?

Thanks

**Comment by ankane** [comment]
Hey @robins35, it's not very clean, but you can do:

```yml
<% test_key = "0".b*32 %>
<% lockbox = Lockbox.new(key: test_key, encode: true) %>

one:
  id: 1
  message_text_ciphertext: <%= lockbox.encrypt("message text value") %>
  topic_ciphertext: <%= lockbox.encrypt("topic value") %>
  encrypted_kms_key: <%= KmsEncrypted::Box.new.encrypt(test_key, context: {model_name: "ChatMessage", model_id: 1}) %>
```
