### ISSUE TITLE
Backwards compatibility from transitioning from lockbox to kms_encrypted

### ISSUE THREAD

**Issue by Aurea-Li** [ankane/kms_encrypted#41]
We're in the middle of transitioning some attributes from being encrypted by the `lockbox` gem to the `kms_encrypted` gem. In the scenario where this change is rolled out and then we have to do a rollback, there can be newly written entries in the database that are encrypted with `kms_encrypted` that is inaccessible to decryption by lockbox. In other words, any new entries being written by kms_encrypted gem will not be backwards compatible with the lockbox gem. This is an issue for us. Do you have any suggestions for dealing with this problem?

For the lockbox gem today, the way we handle this issue (key rotation for lockbox) is by adding the new key to `previous_keys` and deploying before actually rotating the key.

```
lockbox:
  master_key: lockbox_master_key;1
  previous_keys:
  - lockbox_master_key;1
  - lockbox_master_key;2
  ```
  
  Then we update `master_key` to be `GCSM;lockbox_master_key;2`. That way if we ever rollback lockbox still has access to both keys and can decrypt all files.
